---
- name: Create GPO to configure power settings
  ansible.windows.win_shell: |
    Import-Module GroupPolicy -Verbose:$false

    $GPOName = "Configure Power Settings"
    $GPOExists = Get-GPO -Name $GPOName -ErrorAction SilentlyContinue

    if (! $GPOExists) {
      Write-Host "Creating GPO..."
      New-GPO -Name $GPOName | Out-Null

      $Domain = Get-ADDomain
      $Forest = $Domain.Forest
      $DN = $Domain.DistinguishedName
      $TargetOU = $DN

      Write-Host "Enabling High Performance Power Plan..."

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\Software\Policies\Microsoft\Power\PowerSettings';
      }

      try {
          Set-GPRegistryValue @Params -ValueName "ActivePowerScheme" -Value "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c" -Type String | Out-Null
      } catch {
          Write-Error "Error while configuring Power Plan policy!"
      }

      Write-Host "Disabling System Sleep Timeout..."

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\Software\Policies\Microsoft\Power\PowerSettings\29F6C1DB-86DA-48C5-9FDB-F2B67B1F44DA';
      }

      try {
          Set-GPRegistryValue @Params -ValueName "ACSettingIndex" -Value 0 -Type DWORD | Out-Null
      } catch {
          Write-Error "Error while configuring System Sleep Timeout policy!"
      }

      Write-Host "Disabling Unattended Sleep Timeout..."

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\Software\Policies\Microsoft\Power\PowerSettings\7bc4a2f9-d8fc-4469-b07b-33eb785aaca0';
      }

      try {
          Set-GPRegistryValue @Params -ValueName "ACSettingIndex" -Value 0 -Type DWORD | Out-Null
      } catch {
          Write-Error "Error while configuring System Sleep Timeout policy!"
      }

      Write-Host "Disabling Display Timeout..."

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\Software\Policies\Microsoft\Power\PowerSettings\3C0BC021-C8A8-4E07-A973-6B14CBCB2B7E';
      }

      try {
          Set-GPRegistryValue @Params -ValueName "ACSettingIndex" -Value 0 -Type DWORD | Out-Null
      } catch {
          Write-Error "Error while configuring System Sleep Timeout policy!"
      }

      Write-Host "Configuring Security Filter..."

      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Computers" -TargetType Group | Out-Null
      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Users" -TargetType User | Out-Null

      Write-Host "Linking and enabling new GPO..."

      New-GPLink -Name $GPOName -Target $TargetOU -LinkEnabled Yes -Enforced Yes | Out-Null
    }
