---
- name: Create GPO to enable RDP
  ansible.windows.win_shell: |
    Import-Module GroupPolicy -Verbose:$false

    $GPOName = "Enable RDP"
    $GPOExists = Get-GPO -Name $GPOName -ErrorAction SilentlyContinue

    if (! $GPOExists) {
      Write-Host "Creating GPO..."
      New-GPO -Name $GPOName | Out-Null

      $Domain = Get-ADDomain
      $Forest = $Domain.Forest
      $DN = $Domain.DistinguishedName
      $TargetOU = $DN

      Write-Host "Configuring RDP service..."

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server';
      }

      try {
          Set-GPRegistryValue @Params -ValueName 'fDenyTSConnections' -Value 0 -Type DWord | Out-Null
      } catch { 
          Write-Error "Error while configuring RDP policy!"
      }

      $Params = @{
          Name = $GPOName;
          Key = 'HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp';
      }

      try {
          Set-GPRegistryValue @Params -ValueName 'UserAuthentication' -Value 1 -Type DWord | Out-Null
      } catch { 
          Write-Error "Error while configuring NLA policy!"
      }

      Write-Host "Configuring Firewall rules..."

      $PolicyStoreName = "$Forest\$GPOName"
      $GPOSessionName = Open-NetGPO -PolicyStore $PolicyStoreName

      New-NetFirewallRule -DisplayName "Allow RDP" -Profile Any -Direction Inbound -GPOSession $GPOSessionName -PolicyStore $GPOName -Protocol TCP -LocalPort 3389 | Out-Null

      Save-NetGPO -GPOSession $GPOSessionName

      Write-Host "Configuring Security Filter..."

      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Computers" -TargetType Group | Out-Null
      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Users" -TargetType User | Out-Null

      Write-Host "Linking and enabling new GPO..."

      New-GPLink -Name $GPOName -Target $TargetOU -LinkEnabled Yes -Enforced Yes | Out-Null
    }
