---
- name: Create GPO to enable WMI
  ansible.windows.win_shell: |
    Import-Module GroupPolicy -Verbose:$false

    $GPOName = "Enable WMI"
    $GPOExists = Get-GPO -Name $GPOName -ErrorAction SilentlyContinue

    if (! $GPOExists) {
      Write-Host "Creating GPO..."
      New-GPO -Name $GPOName | Out-Null

      $Domain = Get-ADDomain
      $Forest = $Domain.Forest
      $DN = $Domain.DistinguishedName
      $TargetOU = $DN

      Write-Host "Configuring Firewall rules..."

      $PolicyStoreName = "$Forest\$GPOName"
      $GPOSessionName = Open-NetGPO -PolicyStore $PolicyStoreName
      
      New-NetFirewallRule -DisplayName "Allow WMI (ASync-In)" -Profile Any -Direction Inbound -GPOSession $GPOSessionName -PolicyStore $GPOName -Protocol TCP -LocalPort Any -Program "%systemroot%\system32\wbem\unsecapp.exe" | Out-Null
      New-NetFirewallRule -DisplayName "Allow WMI (DCOM-In)" -Profile Any -Direction Inbound -GPOSession $GPOSessionName -PolicyStore $GPOName -Protocol TCP -LocalPort 135 -Program "%SystemRoot%\system32\svchost.exe" | Out-Null
      New-NetFirewallRule -DisplayName "Allow WMI (WMI-In)" -Profile Any -Direction Inbound -GPOSession $GPOSessionName -PolicyStore $GPOName -Protocol TCP -LocalPort Any -Program "%SystemRoot%\system32\svchost.exe" | Out-Null

      Save-NetGPO -GPOSession $GPOSessionName

      Write-Host "Configuring Security Filter..."

      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Computers" -TargetType Group | Out-Null
      Set-GPPermissions -Name $GPOName -PermissionLevel GpoApply -TargetName "Domain Users" -TargetType User | Out-Null

      Write-Host "Linking and enabling new GPO..."

      New-GPLink -Name $GPOName -Target $TargetOU -LinkEnabled Yes -Enforced Yes | Out-Null
    }
